export { default as SvgArrow } from './Arrow'
export { default as SvgCompleteIcon } from './CompleteIcon'
export { default as SvgReferralLink } from './ReferralLink'
export { default as SvgTick } from './Tick'
export { default as SvgTokenovaIcon } from './TokenovaIcon'
export { default as SvgTonConnectIcon } from './TonConnectIcon'
export { default as SvgTonstarterIcon } from './TonstarterIcon'
export { default as SvgTonupIcon } from './TonupIcon'
